# Generated by Django 5.1.6 on 2025-03-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnomart', '0002_category_remove_product_created_at_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
